apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v2-providers
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.providers.name }}{{ .Values.ingress.domain }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nanna.name" . }}
                port:
                  number: {{ .Values.service.http.externalPort }}
