image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

secrets:
  psql-credentials:
    - SPRING_DATASOURCE_USERNAME
    - SPRING_DATASOURCE_PASSWORD

